In [1]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

from transformers import TFBertModel, BertTokenizer

## Load training data from directory

In [8]:
import re
path = "Public Laws_copy/12-21-2018_115-370"
test_string = data_folder = os.path.basename(path)
pattern = r".+_(.+)"
matches = re.match(pattern, test_string)
prefix = matches.group(1)
prefix

'115-370'

In [12]:
def process_training_data(path):
    data_folder = os.path.basename(path)
    pattern = r".+_(.+)"
    matches = re.match(pattern, data_folder)
    prefix = matches.group(1)
    x1_filepath = os.path.join(path, prefix + ".txt")
    x2_filepath = os.path.join(path, prefix + "_series.txt")
    y_filepath = os.path.join(path, prefix + "_label.txt")
    y = tf.io.read_file(y_filepath)
    x1 = tf.io.read_file(x1_filepath)
    x2 = tf.io.read_file(x2_filepath)
    return x1, x2, y
    
plaw_data_path = "Public Laws_copy/12-21-2018_115-370"
x1, x2, y = process_training_data(plaw_data_path)

In [15]:
y

<tf.Tensor: shape=(), dtype=string, numpy=b"Hi I'm a label">

## Load BERT Model

In [2]:
bert = TFBertModel.from_pretrained("bert-base-uncased")
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

## Messing Around

In [3]:
text = "I am a sentence. Look at me!"
encoded_input = tokenizer(text, return_tensors='tf')
print(encoded_input)

{'input_ids': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=
array([[ 101, 1045, 2572, 1037, 6251, 1012, 2298, 2012, 2033,  999,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 11), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


## Back to it

In [ ]:
# input = batch tokenize my text
# output = bert(input)